// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh31dG71RtwDIh1KrSsVobhfoDNorQ0YA',
    appId: '1:935659627808:web:2177eff6c431c7eceb6345',
    messagingSenderId: '935659627808',
    projectId: 'rxmeet-3f5b6',
    authDomain: 'rxmeet-3f5b6.firebaseapp.com',
    storageBucket: 'rxmeet-3f5b6.firebasestorage.app',
    measurementId: 'G-S56VNTBWM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD73XWzqEF121lrVlJK-n__ftCnr-gA51M',
    appId: '1:935659627808:android:c3c66b4a53c5a650eb6345',
    messagingSenderId: '935659627808',
    projectId: 'rxmeet-3f5b6',
    storageBucket: 'rxmeet-3f5b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQXOf1VfptMgDLBO7Uy90IpIvDVyjd1B4',
    appId: '1:935659627808:ios:f6fdb1111777e6b0eb6345',
    messagingSenderId: '935659627808',
    projectId: 'rxmeet-3f5b6',
    storageBucket: 'rxmeet-3f5b6.firebasestorage.app',
    iosBundleId: 'com.example.smartGatewayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQXOf1VfptMgDLBO7Uy90IpIvDVyjd1B4',
    appId: '1:935659627808:ios:f6fdb1111777e6b0eb6345',
    messagingSenderId: '935659627808',
    projectId: 'rxmeet-3f5b6',
    storageBucket: 'rxmeet-3f5b6.firebasestorage.app',
    iosBundleId: 'com.example.smartGatewayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh31dG71RtwDIh1KrSsVobhfoDNorQ0YA',
    appId: '1:935659627808:web:cfb427736b889f43eb6345',
    messagingSenderId: '935659627808',
    projectId: 'rxmeet-3f5b6',
    authDomain: 'rxmeet-3f5b6.firebaseapp.com',
    storageBucket: 'rxmeet-3f5b6.firebasestorage.app',
    measurementId: 'G-SWXP467TLH',
  );
}
